### ISSUE TITLE
run 'make doc-clean' everytime before a build, if not already the case

### ISSUE THREAD

**Issue by jakobkroeker** [robertwb/sage-patchbot#53]
since building sage docs may sometimes fail,
I suggest always run  'make doc-clean' before a build by patchbot

Alternative: if 'make doc' fails, run 'make doc-clean; make doc'  once by the patchbot
if it is not already done so

Remark: recently I got 
```
[reference] WARNING: Unable to fetch /home/jkroeker/Projects/sage-patchbot/src/doc/output/doctrees/en/reference/modfrm_hecketriangle/environment.pickle
Error building the documentation.
Traceback (most recent call last):
  File "/home/jkroeker/Projects/sage-patchbot/src/doc/common/builder.py", line 1490, in <module>
    getattr(get_builder(name), type)()
  File "/home/jkroeker/Projects/sage-patchbot/src/doc/common/builder.py", line 291, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "/home/jkroeker/Projects/sage-patchbot/src/doc/common/builder.py", line 515, in _wrapper
    getattr(DocBuilder(self.name, lang), format)(*args, **kwds)
  File "/home/jkroeker/Projects/sage-patchbot/src/doc/common/builder.py", line 109, in f
    execfile(sys.argv[0])
  File "/home/jkroeker/Projects/sage-patchbot/src/doc/common/custom-sphinx-build.py", line 210, in <module>
    raise OSError(ERROR_MESSAGE)
OSError: [reference] WARNING: Unable to fetch /home/jkroeker/Projects/sage-patchbot/src/doc/output/doctrees/en/reference/modfrm_hecketriangle/environment.pickle

make: *** [doc-html] Error 1
Traceback (most recent call last):
  File "/home/jkroeker/Projects/sage-patchbot/local/bin/patchbot/patchbot.py", line 458, in test_a_ticket
    do_or_die("$MAKE")
  File "/home/jkroeker/Projects/sage-patchbot/local/bin/patchbot/util.py", line 107, in do_or_die
    raise exn_class, "%s %s" % (res, cmd)
Exception: 512 $MAKE
Traceback (most recent call last):
  File "/home/jkroeker/Projects/sage-patchbot/local/bin/patchbot/patchbot.py", line 458, in test_a_ticket
    do_or_die("$MAKE")
  File "/home/jkroeker/Projects/sage-patchbot/local/bin/patchbot/util.py", line 107, in do_or_die
    raise exn_class, "%s %s" % (res, cmd)
Exception: 512 $MAKE
```
or is that a different issue?

**Comment by fchapoton** [comment]
This is now the case:
```
    do_or_die("$MAKE doc-clean")
    do_or_die("$MAKE")
```
