### ISSUE TITLE
stops with urllib2.HTTPError

### ISSUE THREAD

**Issue by rwst** [robertwb/sage-patchbot#81]
```
ralf@ark:~/patchbot/sage> ./sage -patchbot
[2016-06-12 06:42:17] Launching patchbot 2.5.7 with SAGE_ROOT=/home/ralf/patchbot/sage
[2016-06-12 06:42:17] Getting trusted author list...
WARNING: Do not use this copy of sage while the patchbot is running.
'/home/ralf/patchbot/sage'/sage -i ccache
make -j4 build/make/Makefile
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: Entering directory '/home/ralf/patchbot/sage'
make[1]: 'build/make/Makefile' is up to date.
make[1]: Leaving directory '/home/ralf/patchbot/sage'
build/bin/sage-logger \
        "cd build/make && ./install 'all-toolchain'" logs/install.log
Nothing to (re)build / all up-to-date.

make -j4 build/make/Makefile
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: Entering directory '/home/ralf/patchbot/sage'
make[1]: 'build/make/Makefile' is up to date.
make[1]: Leaving directory '/home/ralf/patchbot/sage'
build/bin/sage-logger \
        "cd build/make && ./install 'ccache'" logs/install.log
Nothing to (re)build / all up-to-date.
[2016-06-12 06:42:22] Check base.
git checkout patchbot/base
Already on 'patchbot/base'
git fetch git://github.com/sagemath/sage.git +develop:patchbot/base_upstream
[2016-06-12 06:42:26] testing given ticket #0
[2016-06-12 06:42:26] testing the base



============================== 0 ==============================
base
score = 100



[2016-06-12 06:42:26] #0: init phase
fatal: Not a valid object name patchbot/ticket_upstream
Traceback (most recent call last):
  File "/home/ralf/patchbot/sage/local/bin/patchbot/patchbot.py", line 1289, in report_ticket
    describe_branch('patchbot/ticket_upstream', tag_only=True)]
  File "/home/ralf/patchbot/sage/local/bin/patchbot/util.py", line 238, in describe_branch
    universal_newlines=True)
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'describe', '--tags', '--match', '[0-9].[0-9]*', 'patchbot/ticket_upstream']' returned non-zero exit status 128
REPORT
{'base': '7.3.beta3',
 'deps': [],
 'machine': ['openSUSE', '42.1', 'x86_64', '4.1.21-14-default', 'ark'],
 'owner': 'unknown owner',
 'patchbot_version': u'2.5.7',
 'plugins': (),
 'spkgs': [],
 'status': 'Pending',
 'time': '2016-06-12 06:42:26',
 'user': 'ralf'}
0: Pending
Traceback (most recent call last):
  File "/home/ralf/patchbot/sage/local/bin/patchbot/patchbot.py", line 1469, in <module>
    main(args)
  File "/home/ralf/patchbot/sage/local/bin/patchbot/patchbot.py", line 1430, in main
    res = patchbot.test_a_ticket(0)
  File "/home/ralf/patchbot/sage/local/bin/patchbot/patchbot.py", line 977, in test_a_ticket
    self.report_ticket(ticket, status='Pending', log=log)
  File "/home/ralf/patchbot/sage/local/bin/patchbot/patchbot.py", line 1333, in report_ticket
    fields, files))
  File "/home/ralf/patchbot/sage/local/bin/patchbot/http_post_file.py", line 37, in post_multipart
    return urlopen(r).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 405: METHOD NOT ALLOWED
```

**Comment by fchapoton** [comment]
you need to add the option --server=https://patchbot.sagemath.org

this will be hardcoded in the next versions of the bot

2016-06-12 8:46 GMT+02:00 Ralf Stephan <notifications@github.com>:

**Comment by rwst** [comment]
Thanks, it's running now.
